name: Format Code

on:
  workflow_call:
    inputs:
      pnpm-version:
        description: The version of pnpm to use
        required: false
        default: "10"
        type: string
      node-version:
        description: The version of Node.js to use
        required: false
        default: 22
        type: number

jobs:
  format:
    name: Format Code
    uses: fantacovid-19/fantacovid-19/.github/workflows/reusable-pnpm-jobs.yml@main
    with:
      script: "format:check"
      pnpm-version: ${{ inputs.pnpm-version }}
      node-version: ${{ inputs.node-version }}
